### ISSUE TITLE
Improve time complexity 

### ISSUE THREAD

**Issue by ghost** [Aravindambalavanan/Leetcode_Top_Interview_150#5]
https://github.com/Aravindambalavanan/Leetcode_Top_Interview_150/blob/ba9b2a6a1eb77aff54960b77cafadae9da695ee2/Hashmap/Two%20Sum/TwoSum.java#L5-L11

The current solution uses O(n^2), use a hashmap to reduce the time complexity to O(n)

**Comment by Aravindambalavanan** [comment]
Solution updated
